services:
  web:
    restart: always
    build: .
    container_name: blog-itea-web
    command: ["./entrypoint.sh"]
    env_file:
      - .env
    ports:
      - "8002:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - blog-itea-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: "postgres:latest"
    container_name: blog-itea-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - blog-itea-db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - blog-itea-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: blog-tea-pgadmin
    ports:
      - "3333:80"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - blog-itea-pgadmin-data:/var/lib/pgadmin
    networks:
      - blog-itea-network

volumes:
  blog-itea-db-data:
    driver: local
  blog-itea-pgadmin-data:
    driver: local

networks:
  blog-itea-network:
    driver: bridge
