# Generated by Django 5.1 on 2024-09-16 18:45

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_apitoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to=accounts.utils.get_user_directory_path),
        ),
    ]
