# Generated by Django 5.1 on 2024-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('name', 'year', 'time'), name='unique_movie_constraint'),
        ),
    ]
